name: Flow-CI

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  Build_Flow:
    name: Build Flow project    
    runs-on: windows-latest

    steps:
    - name: Clone repo
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore "Flow/Flow.sln"
    - name: Build
      run: dotnet build "Flow/Flow.sln" --no-restore
      
  Test_Flow:
    name: Test Flow project
    runs-on: windows-latest
    
    steps:
    - name: Clone repo
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore "FlowTests/FlowTests.sln"
    - name: Build
      run: dotnet build "FlowTests/FlowTests.sln" --no-restore
    - name: Test
      run: dotnet test "FlowTests/**/*.dll" --no-build --verbosity normal
