name: Flow-CI

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  Build_Flow:
    name: Test Flow project
    runs-on: windows-latest
    
    steps:
    - name: Clone repo
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
       dotnet-version: 5.x
    - name: Restore NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.NuGetAPIKey }}
        nuget-version: '5.x'
    - name: Restore Flow dependencies
      run: dotnet restore "Flow/Flow.sln"
    - name: Restore FlowTests dependencies
      run: dotnet restore "FlowTests/FlowTests.sln"
    - name: Build Flow
      run: dotnet build "Flow/Flow.sln" --no-restore
    - name: Build FlowTests
      run: dotnet build "FlowTests/FlowTests.sln" --no-restore
    - name: Test
      run: dotnet test "FlowTests/**/FlowTests.dll" --verbosity normal
