name: Flow-CI

on: [push, pull_request]

env:
  BRANCH_NAME: noBranch

jobs:
  Build_Flow:
    name: Build Flow
    runs-on: windows-latest 

    steps:
    - name: Clone repo
      uses: actions/checkout@v2

    - name: Defining a branch
      run: |
        Write-Host ${{ env:$GITHUB_REF }}
        .\Utils\DefineBranch.ps1 -BranchHead ${{ env:$GITHUB_REF }}
      shell: powershell

    - name: Update release version
      run: .\Utils\GetNewVersion.ps1 -BranchName ${{ env:$BRANCH_NAME }}
      shell: powershell

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
       dotnet-version: 5.x

    - name: Restore NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.NuGetAPIKey }}
        nuget-version: '5.x'

    - name: Restore dependencies
      run: |
        dotnet restore "Flow/Flow.sln"
        dotnet restore "FlowTests/FlowTests.sln"

    - name: Build
      run: |
        dotnet build "Flow/Flow.sln" --no-restore
        dotnet build "FlowTests/FlowTests.sln" --no-restore

    - name: Test
      run: dotnet test "FlowTests/FlowTests.sln" --no-build --verbosity normal
